---
- name: Running show commands on Cisco IOS
  hosts: routers
  gather_facts: false

  tasks:
    - name: BGP config
      ios_config: #ansible module
        save_when: modified
        lines: #commands to run
          - bgp log-neighbor-changes
          - network 192.168.66.0
          - neighbor "{{ item }}" remote-as 65535
        parents: router bgp 65535
      with_items:
          - 192.168.66.16
          - 192.168.66.15
      
      register: output    #register the output in a variable named output

    - debug: var=output.stdout_lines   #print the variable at the console line by line

...
